### ISSUE TITLE
[Feature] Add multiple emojis

### ISSUE THREAD

**Issue by Nitesh-thapliyal** [Bauddhik-Geeks/Emoji-Flicker#1]

**Comment by rhvsingh** [comment]
I want to work on this issue.

**Comment by rishigupta1109** [comment]
I would like to work on this.

**Comment by adityamangal1** [comment]
Go ahead @rishigupta1109

**Comment by rishigupta1109** [comment]
@adityamangal1 please ,assign it to me😃

**Comment by Nitesh-thapliyal** [comment]
Hey @rishigupta1109 can you create PR again, earlier you just simply added emoji but in the code it was onclick event , when someone click on emoji then emoji changes but in your case you just displayed emojis in line

**Comment by rishigupta1109** [comment]
I had added a different onclick event and it was working perfectly. I'll check it and will create a new pr

**Comment by rishigupta1109** [comment]
![2021-10-02 11-39-19](https://user-images.githubusercontent.com/84670640/135705729-809cd83d-68a3-4815-81a3-2914e1c7151d.gif)

**Comment by rishigupta1109** [comment]
this is how its looking in my pc
I am not able to create a pr github is saying that both repo are at same level
also there is a onlclick function in my code

**Comment by rishigupta1109** [comment]
![efss](https://user-images.githubusercontent.com/84670640/135705846-9339c63c-e112-4d2c-a989-35bb50dd4c47.PNG)

**Comment by Nitesh-thapliyal** [comment]
earlier we merged the code but it was just displayed as it is without on click, therefore we need to revert that PR 😅

**Comment by rishigupta1109** [comment]
Np.Does I need to do something from my end or You can revert it back to that pr?

**Comment by Nitesh-thapliyal** [comment]
> Np.Does I need to do something from my end or You can revert it back to that pr?

reverted already, now you need to PR again

**Comment by rishigupta1109** [comment]
I am not able to create pull request
![abcd](https://user-images.githubusercontent.com/84670640/135725568-cc67ac0e-c07c-4a33-87f5-c615091d4a34.PNG)

**Comment by rishigupta1109** [comment]
done😃
