### ISSUE TITLE
[Fix] Change the theme of Emoji-Flicker

### ISSUE THREAD

**Issue by Nitesh-thapliyal** [Bauddhik-Geeks/Emoji-Flicker#2]

**Comment by adityarawat1337x** [comment]
Kindly assign this to me.

**Comment by Nitesh-thapliyal** [comment]
> Kindly assign this to me.

Go Ahead @adityarawat1337x  You can join our discord server for any further queries 
Organization link👉 https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks
Discord server link 👉 https://join.bauddhikgeeks.tech/

**Comment by adityarawat1337x** [comment]
Joined..

**Comment by adityarawat1337x** [comment]
@Nitesh-thapliyal i have sent the PR kindly review and merge it.
